export const SELL_ITEM_LOADING = 'SELL_ITEM_LOADING';
export const SELL_ITEM_FETCH_FAILED = 'SELL_ITEM_FETCH_FAILED';
export const ADD_SELL_ITEMS = 'ADD_SELL_ITEMS';
export const SELL_ITEM_POSTING = 'SELL_ITEM_POSTING';
export const SELL_ITEM_POST_FAILED = 'SELL_ITEM_POST_FAILED';
export const ADD_SELL_ITEM = 'ADD_SELL_ITEM';
