export const MARKET_ITEM_LOADING = 'MARKET_ITEM_LOADING';
export const MARKET_ITEM_FETCH_FAILED = 'MARKET_ITEM_FETCH_FAILED';
export const ADD_MARKET_ITEMS = 'ADD_MARKET_ITEMS';
export const ITEM_PURCHASING = 'ITEM_PURCHASING';
export const ITEM_PURCHASE_FAILED = 'ITEM_PURCHASE_FAILED';
export const REMOVE_PURCHASED_ITEM = 'REMOVE_PURCHASED_ITEM';
