export const ITEM_LOADING = 'ITEM_LOADING';
export const ITEM_FETCH_FAILED = 'ITEM_FETCH_FAILED';
export const ADD_ITEMS = 'ADD_ITEMS';
export const ITEM_PURCHASING = 'ITEM_PURCHASING';
export const ITEM_PURCHASE_FAILED = 'ITEM_PURCHASE_FAILED';
export const REMOVE_ITEM = 'REMOVE_ITEM';
